CREATE TABLE `mytable` (
  `column_0` VARCHAR(1024) NULL,
  `Sunday` VARCHAR(1024) NULL,
  `column_2` VARCHAR(1024) NULL,
  `column_3` VARCHAR(1024) NULL,
  `column_4` VARCHAR(1024) NULL,
  `Monday` VARCHAR(1024) NULL,
  `column_6` VARCHAR(1024) NULL,
  `column_7` VARCHAR(1024) NULL,
  `column_8` VARCHAR(1024) NULL,
  `Tuesday` VARCHAR(1024) NULL,
  `column_10` VARCHAR(1024) NULL,
  `column_11` VARCHAR(1024) NULL,
  `column_12` VARCHAR(1024) NULL,
  `Wednesday` VARCHAR(1024) NULL,
  `column_14` VARCHAR(1024) NULL,
  `column_15` VARCHAR(1024) NULL,
  `column_16` VARCHAR(1024) NULL,
  `Thursday` VARCHAR(1024) NULL,
  `column_18` VARCHAR(1024) NULL,
  `column_19` VARCHAR(1024) NULL,
  `column_20` VARCHAR(1024) NULL,
  `Friday` VARCHAR(1024) NULL,
  `column_22` VARCHAR(1024) NULL,
  `column_23` VARCHAR(1024) NULL,
  `column_24` VARCHAR(1024) NULL,
  `Saturday` VARCHAR(1024) NULL,
  `column_26` VARCHAR(1024) NULL,
  `column_27` VARCHAR(1024) NULL,
  `column_28` VARCHAR(1024) NULL,
  `column_29` VARCHAR(1024) NULL,
  `column_30` VARCHAR(1024) NULL
);

INSERT INTO `mytable` (`column_0`,`Sunday`,`column_2`,`column_3`,`column_4`,`Monday`,`column_6`,`column_7`,`column_8`,`Tuesday`,`column_10`,`column_11`,`column_12`,`Wednesday`,`column_14`,`column_15`,`column_16`,`Thursday`,`column_18`,`column_19`,`column_20`,`Friday`,`column_22`,`column_23`,`column_24`,`Saturday`,`column_26`,`column_27`,`column_28`,`column_29`,`column_30`)
VALUES
(NULL,'Gonz','Roland','Junior','Mahir','Gonz','Roland','Junior','Mahir','Gonz','Roland','Junior','Mahir','Gonz','Roland','Junior','Mahir','Gonz','Roland','Junior','Mahir','Gonz','Roland','Junior','Mahir','Gonz','Roland','Junior','Mahir',NULL,NULL),
('0.375',NULL,NULL,NULL,NULL,NULL,'Booked','Booked','Booked','Booked',NULL,NULL,NULL,NULL,NULL,'Booked','Booked','Booked','Booked',NULL,NULL,NULL,NULL,NULL,'Booked','Booked','Booked','Booked',NULL,NULL,'Booked'),
('0.3958333333333333',NULL,NULL,'Booked','Booked',NULL,NULL,'Booked','Booked','Booked','Booked','Booked','Booked',NULL,NULL,'Booked','Booked','Booked','Booked',NULL,NULL,NULL,NULL,NULL,'Booked','Booked','Booked','Booked',NULL,NULL,NULL),
('0.4166666666666667','Booked','Booked',NULL,'Booked',NULL,NULL,'Booked','Booked','Booked','Booked','Booked','Booked','Booked','Booked','Booked','Booked','Booked','Booked','Booked','Booked',NULL,'Booked','Booked','Booked','Booked','Booked','Booked','Booked',NULL,NULL),
('0.4375','Booked','Booked','Booked',NULL,NULL,'Booked',NULL,NULL,'Booked','Booked','Booked','Booked','Booked','Booked','Booked','Booked','Booked','Booked','Booked','Booked',NULL,'Booked','Booked','Booked','Booked','Booked','Booked','Booked',NULL,NULL),
('0.4583333333333333',NULL,NULL,NULL,'Booked',NULL,NULL,'Booked','Booked','Booked',NULL,NULL,NULL,'Booked','Booked','Booked','Booked','Booked','Booked','Booked','Booked',NULL,NULL,'Booked','Booked',NULL,'Booked','Booked',NULL,NULL,NULL),
('0.4791666666666667','Booked','Booked','Booked',NULL,NULL,'Booked','Booked',NULL,'Booked',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Booked',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('0.5',NULL,'Booked',NULL,NULL,'Booked','Booked',NULL,NULL,NULL,'Booked',NULL,'Booked','Booked','Booked','Booked',NULL,NULL,NULL,NULL,NULL,'Booked',NULL,'Booked',NULL,NULL,'Booked',NULL,'Booked',NULL,NULL),
('0.5208333333333334',NULL,NULL,'Booked',NULL,'Booked',NULL,NULL,NULL,'Booked',NULL,NULL,NULL,NULL,NULL,NULL,'Booked','Booked','Booked',NULL,'Booked',NULL,'Booked',NULL,'Booked',NULL,NULL,'Booked',NULL,NULL,NULL),
('0.5416666666666666','Booked',NULL,NULL,'Booked','Booked',NULL,NULL,NULL,NULL,'Booked',NULL,'Booked','Booked','Booked','Booked','Booked',NULL,NULL,NULL,'Booked','Booked',NULL,'Booked','Booked','Booked','Booked','Booked','Booked',NULL,NULL),
('0.5625',NULL,NULL,'Booked',NULL,NULL,'Booked',NULL,'Booked',NULL,NULL,'Booked','Booked','Booked',NULL,NULL,NULL,'Booked',NULL,NULL,NULL,NULL,'Booked',NULL,NULL,'Booked','Booked',NULL,'Booked',NULL,NULL),
('0.5833333333333334','Booked',NULL,NULL,NULL,'Booked',NULL,'Booked','Booked','Booked',NULL,'Booked',NULL,NULL,'Booked',NULL,'Booked',NULL,'Booked','Booked','Booked','Booked',NULL,'Booked','Booked',NULL,'Booked','Booked',NULL,NULL,NULL),
('0.6041666666666666',NULL,NULL,'Booked',NULL,NULL,NULL,'Booked',NULL,'Booked',NULL,NULL,'Booked',NULL,'Booked','Booked',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Booked','Booked',NULL,'Booked','Booked',NULL,NULL),
('0.625','Booked','Booked','Booked','Booked',NULL,NULL,NULL,NULL,NULL,'Booked','Booked','Booked',NULL,NULL,NULL,NULL,'Booked','Booked','Booked','Booked','Booked',NULL,'Booked',NULL,'Booked','Booked',NULL,NULL,NULL,NULL),
('0.6458333333333334','Booked',NULL,NULL,'Booked','Booked','Booked',NULL,'Booked',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Booked',NULL,NULL,NULL,NULL,NULL,'Booked','Booked',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('0.6666666666666666',NULL,NULL,'Booked','Booked',NULL,'Booked','Booked','Booked',NULL,NULL,NULL,NULL,NULL,'Booked',NULL,NULL,NULL,NULL,NULL,'Booked','Booked','Booked',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('0.6875',NULL,NULL,NULL,NULL,'Booked','Booked',NULL,'Booked',NULL,NULL,NULL,NULL,NULL,NULL,'Booked','Booked','Booked',NULL,NULL,'Booked',NULL,'Booked',NULL,NULL,'Booked','Booked','Booked',NULL,NULL,NULL),
('0.7083333333333334',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Booked','Booked',NULL,NULL,'Booked','Booked',NULL,NULL,'Booked','Booked',NULL,'Booked',NULL,'Booked','Booked','Booked',NULL,'Booked',NULL,NULL,NULL),
('0.7291666666666666','Booked','Booked','Booked','Booked','Booked',NULL,'Booked','Booked','Booked','Booked','Booked',NULL,'Booked',NULL,NULL,'Booked',NULL,NULL,NULL,'Booked','Booked',NULL,'Booked','Booked','Booked',NULL,'Booked','Booked',NULL,NULL),
('0.75','Booked',NULL,'Booked',NULL,NULL,NULL,NULL,'Booked','Booked',NULL,'Booked','Booked','Booked','Booked','Booked','Booked',NULL,'Booked','Booked',NULL,NULL,NULL,NULL,NULL,'Booked','Booked',NULL,NULL,NULL,NULL),
('0.7708333333333334',NULL,'Booked','Booked',NULL,'Booked',NULL,'Booked',NULL,'Booked','Booked',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
